# Generated by Django 5.0.6 on 2024-05-24 14:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("features", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MaterialisedFeature",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("feature_body", models.JSONField()),
            ],
        ),
    ]
